# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='imageURL',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
