# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 21:00
from __future__ import unicode_literals
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enrich', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_staff',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enrich.Reviews'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enrich.Organization_Staff'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
