# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
            ],
        ),
    ]
