# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 04:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrichuser',
            name='id',
        ),
        migrations.AddField(
            model_name='enrichuser',
            name='school_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enrichuser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='enrichuser', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
